import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { useData } from '../contexts/DataContext';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../components/ui/select';
import { Plus, X, Upload, Image, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { SchoolCombobox } from '../components/SchoolCombobox';
import { schools } from '../data/schools';
import { addCustomSchool, getAllSchools } from '../lib/schoolStorage';
import { fetchSchoolsProxy } from '../lib/schoolsApi';

export function AddIntern() {
  const navigate = useNavigate();
  const { addIntern, mentors, isLoading: isDataLoading } = useData();
  const [isLoading, setIsLoading] = useState(false);
  const [errors, setErrors] = useState<{[key: string]: string}>({});

  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    address: '',
    socialMedia: '',
    school: '',
    major: '',
    location: '',
    division: '',
    mentorId: '',
    periodStart: '',
    periodEnd: '',
    impression: '',
    message: '',
  });

  const [photoPreview, setPhotoPreview] = useState<string>('');
  const [galleryPreviews, setGalleryPreviews] = useState<string[]>([]);
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [galleryFiles, setGalleryFiles] = useState<File[]>([]);
    // Load custom schools + default schools
  const [allSchools, setAllSchools] = useState(() => getAllSchools(schools));

  // Effect: sync custom schools saat component mount
  useEffect(() => {
    setAllSchools(getAllSchools(schools));
  }, []);

  const handleAddCustomSchool = (schoolName: string) => {
    const added = addCustomSchool(schoolName);
    if (added) {
      const updated = getAllSchools(schools);
      setAllSchools(updated);
      toast.success(`"${schoolName}" ditambahkan ke daftar kampus!`);
    } else {
      toast.info(`"${schoolName}" sudah ada di daftar.`);
    }
    return added;
  };
  
  // Refs for file inputs
  const photoInputRef = useRef<HTMLInputElement>(null);
  const galleryInputRef = useRef<HTMLInputElement>(null);

  const validateForm = () => {
    const newErrors: {[key: string]: string} = {};
    
    // Data Pribadi
    if (!formData.name.trim()) {
      newErrors.name = 'Nama lengkap harus diisi';
    }
    if (!formData.phone.trim()) {
      newErrors.phone = 'Nomor HP harus diisi';
    } else if (!/^[0-9+\-\s]+$/.test(formData.phone)) {
      newErrors.phone = 'Format nomor HP tidak valid';
    }
    if (!formData.email.trim()) {
      newErrors.email = 'Email harus diisi';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Format email tidak valid';
    }
    if (!formData.address.trim()) {
      newErrors.address = 'Alamat harus diisi';
    }
    if (!photoPreview) {
      newErrors.photo = 'Foto profil harus diupload';
    }
    
    // Data Akademik
    if (!formData.school.trim()) {
      newErrors.school = 'Kampus/Sekolah harus diisi';
    }
    if (!formData.major.trim()) {
      newErrors.major = 'Jurusan harus diisi';
    }
    
    // Data Magang
    if (!formData.location.trim()) {
      newErrors.location = 'Lokasi PLN harus diisi';
    }
    if (!formData.division.trim()) {
      newErrors.division = 'Divisi harus diisi';
    }
    if (!formData.mentorId) {
      newErrors.mentorId = 'Mentor harus dipilih';
    }
    if (!formData.periodStart) {
      newErrors.periodStart = 'Periode mulai harus diisi';
    }
    if (!formData.periodEnd) {
      newErrors.periodEnd = 'Periode selesai harus diisi';
    } else if (formData.periodStart && new Date(formData.periodStart) >= new Date(formData.periodEnd)) {
      newErrors.periodEnd = 'Tanggal selesai harus setelah tanggal mulai';
    }
    
    // Kesan & Pesan
    if (!formData.impression.trim()) {
      newErrors.impression = 'Kesan harus diisi';
    }
    if (!formData.message.trim()) {
      newErrors.message = 'Pesan harus diisi';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    
    if (!validateForm()) {
      toast.error('Mohon periksa dan lengkapi field yang ditandai merah');
      setIsLoading(false);
      return;
    }

    try {
      // Simulasi delay untuk loading
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Create new intern data (without id and createdAt - will be generated by database)
      const newInternData = {
        ...formData,
        photo:
          photoPreview ||
          'https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400',
        galleryPhotos: galleryPreviews.length > 0 ? galleryPreviews : [],
        status: 'pending' as const,
      };

      const success = await addIntern(newInternData);
      
      if (success) {
        toast.success(
          'Data intern berhasil dikirim! Menunggu approval dari mentor.',
          {
            duration: 4000,
            description: 'Anda akan menerima notifikasi setelah mentor melakukan review.'
          }
        );
        
        // Reset form
        setFormData({
          name: '',
          phone: '',
          email: '',
          address: '',
          socialMedia: '',
          school: '',
          major: '',
          location: '',
          division: '',
          mentorId: '',
          periodStart: '',
          periodEnd: '',
          impression: '',
          message: '',
        });
        setPhotoPreview('');
        setGalleryPreviews([]);
        setPhotoFile(null);
        setGalleryFiles([]);
        
        navigate('/intern');
      }
    } catch (error) {
      toast.error('Terjadi kesalahan saat menyimpan data. Silakan coba lagi.');
    } finally {
      setIsLoading(false);
    }
  };

  // Handle profile photo upload
  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('File harus berupa gambar (JPG, PNG, GIF)');
      return;
    }
    
    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Ukuran file maksimal 5MB');
      return;
    }
    
    setPhotoFile(file);
    
    // Create preview using FileReader
    const reader = new FileReader();
    reader.onloadend = () => {
      setPhotoPreview(reader.result as string);
      toast.success('Foto profil berhasil dipilih');
    };
    reader.readAsDataURL(file);
  };

  // Remove profile photo
  const removeProfilePhoto = () => {
    setPhotoPreview('');
    setPhotoFile(null);
    if (photoInputRef.current) {
      photoInputRef.current.value = '';
    }
    toast.info('Foto profil dihapus');
  };

  // Handle gallery photos upload
  const handleGalleryUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    
    const newPreviews: string[] = [];
    const newFiles: File[] = [];
    let hasError = false;
    
    Array.from(files).forEach((file) => {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        toast.error(`File ${file.name} bukan gambar`);
        hasError = true;
        return;
      }
      
      // Validate file size (max 5MB each)
      if (file.size > 5 * 1024 * 1024) {
        toast.error(`File ${file.name} melebihi 5MB`);
        hasError = true;
        return;
      }
      
      newFiles.push(file);
      
      // Create preview
      const reader = new FileReader();
      reader.onloadend = () => {
        newPreviews.push(reader.result as string);
        if (newPreviews.length === newFiles.length) {
          setGalleryPreviews([...galleryPreviews, ...newPreviews]);
          setGalleryFiles([...galleryFiles, ...newFiles]);
          if (!hasError) {
            toast.success(`${newFiles.length} foto berhasil ditambahkan`);
          }
        }
      };
      reader.readAsDataURL(file);
    });
    
    // Reset input
    if (galleryInputRef.current) {
      galleryInputRef.current.value = '';
    }
  };

  const removeGalleryPhoto = (index: number) => {
    setGalleryPreviews(galleryPreviews.filter((_, i) => i !== index));
    setGalleryFiles(galleryFiles.filter((_, i) => i !== index));
    toast.info('Foto kenangan dihapus');
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mx-auto max-w-3xl">
        <div className="mb-8">
          <h1 className="mb-2 text-3xl font-bold text-blue-900 dark:text-white">
            Tambah Data Intern
          </h1>
          <p className="text-gray-600 dark:text-gray-300">
            Isi formulir di bawah untuk mendaftar sebagai intern PLN
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Data Pribadi</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="name" className={errors.name ? 'text-red-600' : ''}>
                  Nama Lengkap <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => {
                    setFormData({ ...formData, name: e.target.value });
                    if (errors.name) {
                      setErrors({ ...errors, name: '' });
                    }
                  }}
                  placeholder="Masukkan nama lengkap"
                  className={errors.name ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.name && (
                  <p className="text-red-500 text-sm mt-1">{errors.name}</p>
                )}
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <Label htmlFor="phone" className={errors.phone ? 'text-red-600' : ''}>
                    No. HP <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => {
                      setFormData({ ...formData, phone: e.target.value });
                      if (errors.phone) {
                        setErrors({ ...errors, phone: '' });
                      }
                    }}
                    placeholder="081234567890"
                    className={errors.phone ? 'border-red-500 focus-visible:border-red-500' : ''}
                    disabled={isLoading}
                    required
                  />
                  {errors.phone && (
                    <p className="text-red-500 text-sm mt-1">{errors.phone}</p>
                  )}
                </div>
                <div>
                  <Label htmlFor="email" className={errors.email ? 'text-red-600' : ''}>
                    Email <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => {
                      setFormData({ ...formData, email: e.target.value });
                      if (errors.email) {
                        setErrors({ ...errors, email: '' });
                      }
                    }}
                    placeholder="email@example.com"
                    className={errors.email ? 'border-red-500 focus-visible:border-red-500' : ''}
                    disabled={isLoading}
                    required
                  />
                  {errors.email && (
                    <p className="text-red-500 text-sm mt-1">{errors.email}</p>
                  )}
                </div>
              </div>

              <div>
                <Label htmlFor="socialMedia">Sosial Media</Label>
                <Input
                  id="socialMedia"
                  value={formData.socialMedia}
                  onChange={(e) =>
                    setFormData({ ...formData, socialMedia: e.target.value })
                  }
                  placeholder="@username atau link profil"
                  disabled={isLoading}
                />
              </div>

              <div>
                <Label htmlFor="address" className={errors.address ? 'text-red-600' : ''}>
                  Alamat <span className="text-red-500">*</span>
                </Label>
                <Textarea
                  id="address"
                  value={formData.address}
                  onChange={(e) => {
                    setFormData({ ...formData, address: e.target.value });
                    if (errors.address) {
                      setErrors({ ...errors, address: '' });
                    }
                  }}
                  placeholder="Alamat lengkap"
                  rows={3}
                  className={errors.address ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.address && (
                  <p className="text-red-500 text-sm mt-1">{errors.address}</p>
                )}
              </div>

              <div>
                <Label className={errors.photo ? 'text-red-600' : ''}>Foto Profil <span className="text-red-500">*</span></Label>
                {errors.photo && (
                  <p className="text-red-500 text-sm mt-1">{errors.photo}</p>
                )}
                <div className="mt-2">
                  {/* Hidden file input */}
                  <input
                    ref={photoInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handlePhotoUpload}
                    className="hidden"
                    id="photo-upload"
                    disabled={isLoading}
                  />
                  
                  {photoPreview ? (
                    <div className="flex items-center gap-4">
                      <div className="relative">
                        <img
                          src={photoPreview}
                          alt="Preview foto profil"
                          className="size-24 rounded-full object-cover border-4 border-blue-100 shadow-md"
                        />
                        <button
                          type="button"
                          onClick={removeProfilePhoto}
                          className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full p-1 hover:bg-red-600 transition-colors shadow-md"
                          disabled={isLoading}
                          title="Hapus foto"
                        >
                          <X className="size-4" />
                        </button>
                      </div>
                      <div className="flex flex-col gap-2">
                        <Button
                          type="button"
                          variant="outline"
                          onClick={() => photoInputRef.current?.click()}
                          className="gap-2"
                          disabled={isLoading}
                        >
                          <Upload className="size-4" />
                          Ganti Foto
                        </Button>
                        <p className="text-xs text-gray-500">
                          {photoFile?.name || 'Foto terpilih'}
                        </p>
                      </div>
                    </div>
                  ) : (
                    <div 
                      onClick={() => !isLoading && photoInputRef.current?.click()}
                      className={`border-2 border-dashed rounded-lg p-6 text-center cursor-pointer transition-colors ${
                        isLoading 
                          ? 'border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-slate-800 cursor-not-allowed' 
                          : 'border-gray-300 dark:border-gray-600 hover:border-blue-400 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-slate-800'
                      }`}
                    >
                      <div className="flex flex-col items-center gap-2">
                        <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-slate-700 flex items-center justify-center">
                          <Image className="size-8 text-gray-400" />
                        </div>
                        <div>
                          <p className="font-medium text-gray-700 dark:text-gray-200">Klik untuk upload foto profil</p>
                          <p className="text-sm text-gray-500 dark:text-gray-400">JPG, PNG atau GIF (Max. 5MB)</p>
                        </div>
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          className="mt-2 gap-2"
                          disabled={isLoading}
                        >
                          <Upload className="size-4" />
                          Pilih Foto
                        </Button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Data Akademik</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="school" className={errors.school ? 'text-red-600' : ''}>
                  Kampus/Sekolah <span className="text-red-500">*</span>
                </Label>
                <SchoolCombobox
                  items={allSchools}
                  fetchSchools={fetchSchoolsProxy}
                  onAddCustom={handleAddCustomSchool}
                  value={formData.school}
                  onValueChange={(value) => {
                    setFormData({ ...formData, school: value });
                    if (errors.school) setErrors({ ...errors, school: '' });
                  }}
                  placeholder="Pilih atau cari kampus/sekolah..."
                  searchPlaceholder="Cari kampus atau sekolah..."
                  disabled={isLoading}
                  error={!!errors.school}
                />
                {errors.school && (
                  <p className="text-red-500 text-sm mt-1">{errors.school}</p>
                )}
              </div>

              <div>
                <Label htmlFor="major" className={errors.major ? 'text-red-600' : ''}>
                  Jurusan <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="major"
                  value={formData.major}
                  onChange={(e) => {
                    setFormData({ ...formData, major: e.target.value });
                    if (errors.major) {
                      setErrors({ ...errors, major: '' });
                    }
                  }}
                  placeholder="Nama jurusan"
                  className={errors.major ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.major && (
                  <p className="text-red-500 text-sm mt-1">{errors.major}</p>
                )}
              </div>
            </CardContent>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Data Magang</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="location" className={errors.location ? 'text-red-600' : ''}>
                  Lokasi PLN <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="location"
                  value={formData.location}
                  onChange={(e) => {
                    setFormData({ ...formData, location: e.target.value });
                    if (errors.location) {
                      setErrors({ ...errors, location: '' });
                    }
                  }}
                  placeholder="Contoh: PLN Kantor Pusat Jakarta"
                  className={errors.location ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.location && (
                  <p className="text-red-500 text-sm mt-1">{errors.location}</p>
                )}
              </div>

              <div>
                <Label htmlFor="division" className={errors.division ? 'text-red-600' : ''}>
                  Divisi <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="division"
                  value={formData.division}
                  onChange={(e) => {
                    setFormData({ ...formData, division: e.target.value });
                    if (errors.division) {
                      setErrors({ ...errors, division: '' });
                    }
                  }}
                  placeholder="Contoh: Teknologi Informasi"
                  className={errors.division ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.division && (
                  <p className="text-red-500 text-sm mt-1">{errors.division}</p>
                )}
              </div>

              <div>
                <Label htmlFor="mentor" className={errors.mentorId ? 'text-red-600' : ''}>
                  Mentor <span className="text-red-500">*</span>
                </Label>
                <Select
                  value={formData.mentorId}
                  onValueChange={(value) => {
                    setFormData({ ...formData, mentorId: value });
                    if (errors.mentorId) {
                      setErrors({ ...errors, mentorId: '' });
                    }
                  }}
                  disabled={isLoading || isDataLoading}
                  required
                >
                  <SelectTrigger className={errors.mentorId ? 'border-red-500 focus-visible:border-red-500' : ''}>
                    <SelectValue placeholder={isDataLoading ? 'Memuat mentor...' : 'Pilih mentor'} />
                  </SelectTrigger>
                  <SelectContent>
                    {mentors.map((mentor) => (
                      <SelectItem key={mentor.id} value={mentor.id}>
                        <div className="flex flex-col items-start">
                          <span className="font-medium">{mentor.name}</span>
                          <span className="text-sm text-gray-500">{mentor.division}</span>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.mentorId && (
                  <p className="text-red-500 text-sm mt-1">{errors.mentorId}</p>
                )}
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <Label htmlFor="periodStart" className={errors.periodStart ? 'text-red-600' : ''}>
                    Periode Mulai <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="periodStart"
                    type="date"
                    value={formData.periodStart}
                    onChange={(e) => {
                      setFormData({ ...formData, periodStart: e.target.value });
                      if (errors.periodStart) {
                        setErrors({ ...errors, periodStart: '' });
                      }
                    }}
                    className={errors.periodStart ? 'border-red-500 focus-visible:border-red-500' : ''}
                    disabled={isLoading}
                    required
                  />
                  {errors.periodStart && (
                    <p className="text-red-500 text-sm mt-1">{errors.periodStart}</p>
                  )}
                </div>
                <div>
                  <Label htmlFor="periodEnd" className={errors.periodEnd ? 'text-red-600' : ''}>
                    Periode Selesai <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="periodEnd"
                    type="date"
                    value={formData.periodEnd}
                    onChange={(e) => {
                      setFormData({ ...formData, periodEnd: e.target.value });
                      if (errors.periodEnd) {
                        setErrors({ ...errors, periodEnd: '' });
                      }
                    }}
                    className={errors.periodEnd ? 'border-red-500 focus-visible:border-red-500' : ''}
                    disabled={isLoading}
                    min={formData.periodStart || undefined}
                  />
                  {errors.periodEnd && (
                    <p className="text-red-500 text-sm mt-1">{errors.periodEnd}</p>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Kesan & Pesan</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="impression" className={errors.impression ? 'text-red-600' : ''}>
                  Kesan <span className="text-red-500">*</span>
                </Label>
                <Textarea
                  id="impression"
                  value={formData.impression}
                  onChange={(e) => {
                    setFormData({ ...formData, impression: e.target.value });
                    if (errors.impression) {
                      setErrors({ ...errors, impression: '' });
                    }
                  }}
                  placeholder="Ceritakan kesan Anda selama magang di PLN..."
                  rows={4}
                  className={errors.impression ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.impression && (
                  <p className="text-red-500 text-sm mt-1">{errors.impression}</p>
                )}
                <p className="text-sm text-gray-500 mt-1">
                  Berbagi pengalaman dan pembelajaran yang didapat
                </p>
              </div>

              <div>
                <Label htmlFor="message" className={errors.message ? 'text-red-600' : ''}>
                  Pesan <span className="text-red-500">*</span>
                </Label>
                <Textarea
                  id="message"
                  value={formData.message}
                  onChange={(e) => {
                    setFormData({ ...formData, message: e.target.value });
                    if (errors.message) {
                      setErrors({ ...errors, message: '' });
                    }
                  }}
                  placeholder="Pesan dan saran untuk PLN..."
                  rows={4}
                  className={errors.message ? 'border-red-500 focus-visible:border-red-500' : ''}
                  disabled={isLoading}
                  required
                />
                {errors.message && (
                  <p className="text-red-500 text-sm mt-1">{errors.message}</p>
                )}
                <p className="text-sm text-gray-500 mt-1">
                  Sampaikan apresiasi atau saran untuk kemajuan PLN
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Foto Kenangan</CardTitle>
            </CardHeader>
            <CardContent>
              {/* Hidden file input for gallery */}
              <input
                ref={galleryInputRef}
                type="file"
                accept="image/*"
                multiple
                onChange={handleGalleryUpload}
                className="hidden"
                id="gallery-upload"
                disabled={isLoading}
              />
              
              <div className="mb-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => galleryInputRef.current?.click()}
                  className="gap-2"
                  disabled={isLoading}
                >
                  <Plus className="size-4" />
                  Tambah Foto Kenangan
                </Button>
                <p className="text-sm text-gray-500 mt-2">
                  Tambahkan foto-foto kegiatan selama magang (opsional, max 5MB per foto)
                </p>
              </div>

              {galleryPreviews.length > 0 ? (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-medium text-gray-700">
                      {galleryPreviews.length} foto dipilih
                    </p>
                    {galleryPreviews.length > 0 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => {
                          setGalleryPreviews([]);
                          setGalleryFiles([]);
                          toast.info('Semua foto kenangan dihapus');
                        }}
                        className="text-red-500 hover:text-red-600 hover:bg-red-50 gap-1"
                        disabled={isLoading}
                      >
                        <Trash2 className="size-4" />
                        Hapus Semua
                      </Button>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
                    {galleryPreviews.map((photo, index) => (
                      <div key={index} className="group relative">
                        <img
                          src={photo}
                          alt={`Foto kenangan ${index + 1}`}
                          className="aspect-square w-full rounded-lg object-cover border-2 border-gray-200 shadow-sm hover:shadow-md transition-shadow"
                        />
                        <button
                          type="button"
                          onClick={() => removeGalleryPhoto(index)}
                          className="absolute right-2 top-2 rounded-full bg-red-500 p-1.5 text-white opacity-0 transition-all group-hover:opacity-100 hover:bg-red-600 shadow-md"
                          disabled={isLoading}
                          title="Hapus foto"
                        >
                          <X className="size-3" />
                        </button>
                        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/50 to-transparent p-2 rounded-b-lg opacity-0 group-hover:opacity-100 transition-opacity">
                          <p className="text-white text-xs truncate">
                            {galleryFiles[index]?.name || `Foto ${index + 1}`}
                          </p>
                        </div>
                      </div>
                    ))}
                    {/* Add more button */}
                    <div 
                      onClick={() => !isLoading && galleryInputRef.current?.click()}
                      className={`aspect-square border-2 border-dashed rounded-lg flex flex-col items-center justify-center cursor-pointer transition-colors ${
                        isLoading 
                          ? 'border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-slate-800 cursor-not-allowed' 
                          : 'border-gray-300 dark:border-gray-600 hover:border-blue-400 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-slate-800'
                      }`}
                    >
                      <Plus className="size-8 text-gray-400" />
                      <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Tambah</p>
                    </div>
                  </div>
                </div>
              ) : (
                <div 
                  onClick={() => !isLoading && galleryInputRef.current?.click()}
                  className={`text-center py-12 border-2 border-dashed rounded-lg cursor-pointer transition-colors ${
                    isLoading 
                      ? 'border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-slate-800 cursor-not-allowed' 
                      : 'border-gray-300 dark:border-gray-600 hover:border-blue-400 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-slate-800'
                  }`}
                >
                  <div className="flex flex-col items-center gap-3">
                    <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-slate-700 flex items-center justify-center">
                      <Image className="size-8 text-gray-400" />
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-300 font-medium">Belum ada foto kenangan</p>
                      <p className="text-sm text-gray-400">Klik di sini atau tombol di atas untuk menambah foto</p>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          <div className="flex gap-4">
            <Button type="submit" size="lg" className="flex-1" disabled={isLoading}>
              {isLoading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Menyimpan Data...
                </>
              ) : (
                <>
                  <Plus className="size-4 mr-2" />
                  Submit Data Intern
                </>
              )}
            </Button>
            <Button
              type="button"
              variant="outline"
              size="lg"
              onClick={() => navigate('/intern')}
              disabled={isLoading}
            >
              Batal
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
